// @ts-nocheck

/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_b5b7b1a0 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/zjpshcgztajveubbaxxh/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
// @ts-nocheck
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// This file runs in Supabase Edge Functions (Deno environment)
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL"),
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")
  );

export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();
  const { error } = await supabase.from("kv_store_b5b7b1a0").upsert({
    key,
    value,
  });
  if (error) throw new Error(error.message);
};

export const get = async (key: string): Promise<any> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_b5b7b1a0")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) throw new Error(error.message);

  return data?.value;
};

export const del = async (key: string): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_b5b7b1a0")
    .delete()
    .eq("key", key);

  if (error) throw new Error(error.message);
};

export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client();
  const rows = keys.map((k, i) => ({ key: k, value: values[i] }));

  const { error } = await supabase.from("kv_store_b5b7b1a0").upsert(rows);
  if (error) throw new Error(error.message);
};

export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_b5b7b1a0")
    .select("value")
    .in("key", keys);

  if (error) throw new Error(error.message);

  return data?.map((d: any) => d.value) ?? [];
};

export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client();
  const { error } = await supabase
    .from("kv_store_b5b7b1a0")
    .delete()
    .in("key", keys);

  if (error) throw new Error(error.message);
};

export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client();
  const { data, error } = await supabase
    .from("kv_store_b5b7b1a0")
    .select("key, value")
    .like("key", prefix + "%");

  if (error) throw new Error(error.message);

  return data?.map((d: any) => d.value) ?? [];
};
